/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

#include <unistd.h>
#include <stdio.h>

void delay(void){
	for(uint32_t i = 0; i < 200000; i++);
}

int main(void)
{
	GPIO_Handle_t LED4;
	LED4.pGPIOx = GPIOD;
	LED4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	LED4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	LED4.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_Handle_t LED3;
	LED3.pGPIOx = GPIOD;
	LED3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	LED3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	LED3.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_Handle_t LED5;
	LED5.pGPIOx = GPIOD;
	LED5.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	LED5.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED5.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED5.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	LED5.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_Handle_t LED6;
	LED6.pGPIOx = GPIOD;
	LED6.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	LED6.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED6.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED6.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	LED6.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&LED4);
	GPIO_Init(&LED3);
	GPIO_Init(&LED5);
	GPIO_Init(&LED6);


	while(1){
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
		delay();
	}
}
