/*
 * stm32f407xx.h
 *
 *  Created on: Aug 31, 2022
 *      Author: egbra
 */

#ifndef INC_STM32F407XX_H_
#define INC_STM32F407XX_H_


// MEMORY BASE ADDRESSES
#define FLASH_BASEADDR				0x08000000UL
#define SRAM1_BASEADDR				0x20000000UL
#define SRAM2_BASEADDR				0x2001C000UL
#define ROM_BASEADDR				0x1FFF0000UL
#define SRAM						SRAM1_BASEADDR

//PERIPHERAL BASE ADDRESSES
#define PERIPH_BASEADDR				0x40000000UL
#define APB1PERIPH_BASEADDR			PERIPH_BASEADDR
#define APB2PERIPH_BASEADDR			0x40010000UL
#define AHB1PERIPH_BASEADDR			0x40020000UL
#define AHB2PERIPH_BASEADDR			0x50000000UL

// AHB1 PERIPHERAL ADDRESSES
#define GPIOA_BASEADDR				(AHB1PERIPH_BASEADDR + 0x0000UL)
#define GPIOB_BASEADDR				(AHB1PERIPH_BASEADDR + 0x0400UL)
#define GPIOC_BASEADDR				(AHB1PERIPH_BASEADDR + 0x0800UL)
#define GPIOD_BASEADDR				(AHB1PERIPH_BASEADDR + 0x0C00UL)
#define GPIOE_BASEADDR				(AHB1PERIPH_BASEADDR + 0x1000UL)
#define GPIOF_BASEADDR				(AHB1PERIPH_BASEADDR + 0x1400UL)
#define GPIOG_BASEADDR				(AHB1PERIPH_BASEADDR + 0x1800UL)
#define GPIOH_BASEADDR				(AHB1PERIPH_BASEADDR + 0x1C00UL)
#define GPIOI_BASEADDR				(AHB1PERIPH_BASEADDR + 0x2000UL)

// APB1 PERIPHERAL ADDRESSES
#define I2C1_BASEADDR				(APB1PERIPH_BASEADDR + 0x5400UL)
#define I2C2_BASEADDR				(APB1PERIPH_BASEADDR + 0x5800UL)
#define I2C3_BASEADDR				(APB1PERIPH_BASEADDR + 0x5C00UL)

#define SPI2_BASEADDR				(APB1PERIPH_BASEADDR + 0x3800UL)
#define SPI3_BASEADDR				(APB1PERIPH_BASEADDR + 0x3C00UL)

#define USART2_BASEADDR				(APB1PERIPH_BASEADDR + 0x4400UL)
#define USART3_BASEADDR				(APB1PERIPH_BASEADDR + 0x4800UL)
#define UART4_BASEADDR				(APB1PERIPH_BASEADDR + 0x4C00UL)
#define UART5_BASEADDR				(APB1PERIPH_BASEADDR + 0x5000UL)

// APB2 PERIPHERAL ADDRESSES
#define SPI1_BASEADDR				(APB2PERIPH_BASEADDR + 0x3000UL)

#define USART1_BASEADDR				(APB2PERIPH_BASEADDR + 0x1000UL)
#define USART6_BASEADDR				(APB2PERIPH_BASEADDR + 0x1400UL)

#define EXTI_BASEADDR				(APB2PERIPH_BASEADDR + 0x3C00UL)

#define SYSCFG_BASEADDR				(APB2PERIPH_BASEADDR + 0x3800UL)


// GPIO REGISTERS
#define GPIOA_MODER					(GPIOA_BASEADDR + 0x00)
#define GPIOA_OTYPER				(GPIOA_BASEADDR + 0x04)
#define GPIOA_OSPEEDR				(GPIOA_BASEADDR + 0x08)
#define GPIOA_PUPDR					(GPIOA_BASEADDR + 0x0C)
#define GPIOA_IDR					(GPIOA_BASEADDR + 0x10)
#define GPIOA_ODR					(GPIOA_BASEADDR + 0x14)
#define GPIOA_BSRR					(GPIOA_BASEADDR + 0x18)
#define GPIOA_AFRL					(GPIOA_BASEADDR + 0x20)
#define GPIOA_AFRH					(GPIOA_BASEADDR + 0x24)

#define GPIOB_MODER					(GPIOB_BASEADDR + 0x00)
#define GPIOB_OTYPER				(GPIOB_BASEADDR + 0x04)
#define GPIOB_OSPEEDR				(GPIOB_BASEADDR + 0x08)
#define GPIOB_PUPDR					(GPIOB_BASEADDR + 0x0C)
#define GPIOB_IDR					(GPIOB_BASEADDR + 0x10)
#define GPIOB_ODR					(GPIOB_BASEADDR + 0x14)
#define GPIOB_BSRR					(GPIOB_BASEADDR + 0x18)
#define GPIOB_AFRL					(GPIOB_BASEADDR + 0x20)
#define GPIOB_AFRH					(GPIOB_BASEADDR + 0x24)

#define GPIOC_MODER					(GPIOC_BASEADDR + 0x00)
#define GPIOC_OTYPER				(GPIOC_BASEADDR + 0x04)
#define GPIOC_OSPEEDR				(GPIOC_BASEADDR + 0x08)
#define GPIOC_PUPDR					(GPIOC_BASEADDR + 0x0C)
#define GPIOC_IDR					(GPIOC_BASEADDR + 0x10)
#define GPIOC_ODR					(GPIOC_BASEADDR + 0x14)
#define GPIOC_BSRR					(GPIOC_BASEADDR + 0x18)
#define GPIOC_AFRL					(GPIOC_BASEADDR + 0x20)
#define GPIOC_AFRH					(GPIOC_BASEADDR + 0x24)

#define GPIOD_MODER					(GPIOD_BASEADDR + 0x00)
#define GPIOD_OTYPER				(GPIOD_BASEADDR + 0x04)
#define GPIOD_OSPEEDR				(GPIOD_BASEADDR + 0x08)
#define GPIOD_PUPDR					(GPIOD_BASEADDR + 0x0C)
#define GPIOD_IDR					(GPIOD_BASEADDR + 0x10)
#define GPIOD_ODR					(GPIOD_BASEADDR + 0x14)
#define GPIOD_BSRR					(GPIOD_BASEADDR + 0x18)
#define GPIOD_AFRL					(GPIOD_BASEADDR + 0x20)
#define GPIOD_AFRH					(GPIOD_BASEADDR + 0x24)

#define GPIOE_MODER					(GPIOE_BASEADDR + 0x00)
#define GPIOE_OTYPER				(GPIOE_BASEADDR + 0x04)
#define GPIOE_OSPEEDR				(GPIOE_BASEADDR + 0x08)
#define GPIOE_PUPDR					(GPIOE_BASEADDR + 0x0C)
#define GPIOE_IDR					(GPIOE_BASEADDR + 0x10)
#define GPIOE_ODR					(GPIOE_BASEADDR + 0x14)
#define GPIOE_BSRR					(GPIOE_BASEADDR + 0x18)
#define GPIOE_AFRL					(GPIOE_BASEADDR + 0x20)
#define GPIOE_AFRH					(GPIOE_BASEADDR + 0x24)

#define GPIOF_MODER					(GPIOF_BASEADDR + 0x00)
#define GPIOF_OTYPER				(GPIOF_BASEADDR + 0x04)
#define GPIOF_OSPEEDR				(GPIOF_BASEADDR + 0x08)
#define GPIOF_PUPDR					(GPIOF_BASEADDR + 0x0C)
#define GPIOF_IDR					(GPIOF_BASEADDR + 0x10)
#define GPIOF_ODR					(GPIOF_BASEADDR + 0x14)
#define GPIOF_BSRR					(GPIOF_BASEADDR + 0x18)
#define GPIOF_AFRL					(GPIOF_BASEADDR + 0x20)
#define GPIOF_AFRH					(GPIOF_BASEADDR + 0x24)

#define GPIOG_MODER					(GPIOG_BASEADDR + 0x00)
#define GPIOG_OTYPER				(GPIOG_BASEADDR + 0x04)
#define GPIOG_OSPEEDR				(GPIOG_BASEADDR + 0x08)
#define GPIOG_PUPDR					(GPIOG_BASEADDR + 0x0C)
#define GPIOG_IDR					(GPIOG_BASEADDR + 0x10)
#define GPIOG_ODR					(GPIOG_BASEADDR + 0x14)
#define GPIOG_BSRR					(GPIOG_BASEADDR + 0x18)
#define GPIOG_AFRL					(GPIOG_BASEADDR + 0x20)
#define GPIOG_AFRH					(GPIOG_BASEADDR + 0x24)

#define GPIOH_MODER					(GPIOGH_BASEADDR + 0x00)
#define GPIOH_OTYPER				(GPIOGH_BASEADDR + 0x04)
#define GPIOH_OSPEEDR				(GPIOGH_BASEADDR + 0x08)
#define GPIOH_PUPDR					(GPIOGH_BASEADDR + 0x0C)
#define GPIOH_IDR					(GPIOGH_BASEADDR + 0x10)
#define GPIOH_ODR					(GPIOGH_BASEADDR + 0x14)
#define GPIOH_BSRR					(GPIOGH_BASEADDR + 0x18)
#define GPIOH_AFRL					(GPIOGH_BASEADDR + 0x20)
#define GPIOH_AFRH					(GPIOGH_BASEADDR + 0x24)

#define GPIOI_MODER					(GPIOI_BASEADDR + 0x00)
#define GPIOI_OTYPER				(GPIOI_BASEADDR + 0x04)
#define GPIOI_OSPEEDR				(GPIOI_BASEADDR + 0x08)
#define GPIOI_PUPDR					(GPIOI_BASEADDR + 0x0C)
#define GPIOI_IDR					(GPIOI_BASEADDR + 0x10)
#define GPIOI_ODR					(GPIOI_BASEADDR + 0x14)
#define GPIOI_BSRR					(GPIOI_BASEADDR + 0x18)
#define GPIOI_AFRL					(GPIOI_BASEADDR + 0x20)
#define GPIOI_AFRH					(GPIOI_BASEADDR + 0x24)

#endif /* INC_STM32F407XX_H_ */
